from preprocessing_folder.preprocessing_base import PreprocessingBase
from preprocessing_folder.no_preprocessing import NoPreprocessing
from preprocessing_folder.residuals_preprocessing import ResidualsPreprocessing
